gui:
  theme:
    activeBorderColor:
      - '#7aa2f7'
      - bold
    inactiveBorderColor:
      - '#565f89'
    selectedLineBgColor:
      - '#1a1b26'
  language: 'ja'
  mouseEvents: true
git:
  pagers:
    - colorArg: always
