[colors.primary]
background = "#000918"

[cursor]
blink_interval = 400
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 5
y = 0

[general]
live_config_reload = true
import = [
        "~/.config/alacritty/themes/themes/autumn.toml"
]

[terminal]
# args = ["-l","-c",'tmux a -t default || tmux new -s default\; source ~/.config/tmux/default.session.conf']

[terminal.shell]
program = "/opt/homebrew/bin/zellij"
